build:
    environment:
        php:
            version: 7.1
    tests:
        override:
            -
                command: 'vendor/bin/phpunit --coverage-clover=coverage-file'
                coverage:
                    file: 'coverage-file'
                    format: 'clover'
checks:
    php:
        code_rating: true
        duplication: true
